# Generated by Django 5.1.7 on 2025-04-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('stock_level', models.CharField(max_length=20)),
                ('alert_status', models.CharField(max_length=20)),
                ('dealership', models.CharField(max_length=100)),
                ('restock_date', models.DateField(blank=True, null=True)),
                ('restock_recommendation', models.CharField(max_length=100)),
            ],
        ),
    ]
