# Generated by Django 5.1.7 on 2025-04-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='restock_date',
            new_name='last_restocked',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='alert_status',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='restock_recommendation',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='stock_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
